/*
조건에 맞는 도서와 저자 리스트 출력하기 (mysql)

- 카테고리가 '경제'인 것을 추리고 이를 AUTHOR 테이블과 JOIN 한다.
* Pass/1st/00:02:36
*/
SELECT BOOK_ID, AUTHOR_NAME, SUBSTR(PUBLISHED_DATE, 1, 10) AS PUBLISHED_DATE
FROM BOOK
INNER JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE CATEGORY = "경제"
ORDER BY PUBLISHED_DATE;