/*
3월에 태어난 여성 회원 목록 출력하기 (mysql)

- SUBSTR로 월 자리를 추출하도록 한다.
* Fail/1st/00:02:33
*/
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL AND SUBSTR(DATE_OF_BIRTH, 6, 2) = "03"
ORDER BY MEMBER_ID;