/*
상품 별 오프라인 매출 구하기 (mysql)

- JOIN을 하고, GROUP BY로 상품 코드별로 묶고, 조건에 따라 정렬한다.
* Fail/1st/00:04:08
*/
SELECT PRODUCT_CODE, SUM(PRICE) AS SALES
FROM OFFLINE_SALE
INNER JOIN PRODUCT ON OFFLINE_SALE.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;