/*
오랜 기간 보호한 동물(2) (mysql)

- DATETIME의 차이를 이용하여 정렬할 수 있다.
* Fail/1st/00:02:23
*/
SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
FROM ANIMAL_OUTS, ANIMAL_INS
WHERE ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
ORDER BY ANIMAL_OUTS.DATETIME - ANIMAL_INS.DATETIME DESC