/*
오랜 기간 보호한 동물(1) (mysql)

- ANIMAL_INS의 동물 중 ANIMAL_OUTS에 없는 동물들을 날짜 순으로 정렬해서 3개 보이도록 한다.
* Pass/1st/00:05:41
*/
SELECT ANIMAL_INS.NAME, ANIMAL_INS.DATETIME
FROM ANIMAL_INS LEFT OUTER JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_OUTS.DATETIME IS NULL
ORDER BY ANIMAL_INS.DATETIME ASC LIMIT 3;