/*
있었는데요 없었습니다 (mysql)

- JOIN을 이용하여 간단하게 작성할 수 있다.
* Pass/1st/00:04:33
*/
SELECT ANIMAL_INS.ANIMAL_ID AS ANIMAL_ID, ANIMAL_INS.NAME AS NAME
FROM ANIMAL_INS, ANIMAL_OUTS
WHERE ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID AND ANIMAL_INS.DATETIME > ANIMAL_OUTS.DATETIME
ORDER BY ANIMAL_INS.DATETIME ASC