/*
보호소에서 중성화한 동물 (mysql)

- JOIN을 이용하되 LIKE를 이용해서 중성화여부를 체크할 수 있다.
* Pass/1st/00:05:50
*/
SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.ANIMAL_TYPE, ANIMAL_OUTS.NAME
FROM ANIMAL_OUTS, ANIMAL_INS
WHERE ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID AND ANIMAL_INS.SEX_UPON_INTAKE LIKE "Intact%" AND (ANIMAL_OUTS.SEX_UPON_OUTCOME LIKE "Spayed%" OR ANIMAL_OUTS.SEX_UPON_OUTCOME LIKE "Neutered%");